import Link from 'next/link';
import type { Metadata } from 'next';
import { ArrowUpRight, Compass, Sparkles } from 'lucide-react';
import { CATEGORIES } from '@/src/config/categories';

export const metadata: Metadata = { title: 'Categories', description: 'Explore travel stories by air travel, destinations, food, safety, deals, and more.', alternates: { canonical: '/categories' } };

export default function CategoriesPage() {
  return <main className="min-h-screen bg-[#f7f8f6] text-[#19273A]">
    <section className="relative overflow-hidden bg-[#19273A] text-white"><div className="absolute -right-24 -top-32 h-96 w-96 rounded-full bg-[#C9A14A]/20 blur-3xl" /><div className="absolute -bottom-40 left-1/4 h-96 w-96 rounded-full bg-[#3e6384]/30 blur-3xl" /><div className="relative mx-auto max-w-7xl px-4 pb-16 pt-20 sm:px-6 lg:px-8 lg:pb-24 lg:pt-28"><div className="max-w-3xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-semibold text-[#f1d07a]"><Compass className="h-4 w-4" />The GTR story map</div><h1 className="text-4xl font-black tracking-tight sm:text-6xl">Find your next <span className="text-[#C9A14A]">way to travel.</span></h1><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-300">Browse our editorial coverage by the questions travellers ask most—from choosing a flight to finding a better place to stay.</p></div><div className="mt-10 flex flex-wrap gap-3 text-sm text-slate-300"><span className="rounded-full bg-white/10 px-4 py-2">{CATEGORIES.length} editorial sections</span><span className="rounded-full bg-white/10 px-4 py-2">Independent travel reporting</span></div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 lg:px-8 lg:py-20"><div className="mb-10 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-3 text-sm font-bold uppercase tracking-[0.2em] text-[#8A6A20]">Explore the desk</p><h2 className="text-3xl font-black tracking-tight sm:text-4xl">What are you planning?</h2></div><p className="max-w-md text-sm leading-6 text-slate-600">Each section brings together practical guides, news and considered recommendations.</p></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{CATEGORIES.map((category, index) => <Link key={category.slug} href={`/categories/${category.slug}`} className="group relative overflow-hidden rounded-2xl border border-slate-200 bg-white p-6 shadow-sm transition duration-300 hover:-translate-y-1 hover:border-[#C9A14A] hover:shadow-xl"><div className="mb-8 flex items-start justify-between"><span className="flex h-14 w-14 items-center justify-center rounded-2xl bg-[#f4efe2] text-3xl" aria-hidden="true">{category.icon}</span><span className="text-sm font-bold text-slate-400">{String(index + 1).padStart(2, '0')}</span></div><h3 className="text-xl font-black group-hover:text-[#8A6A20]">{category.name}</h3><p className="mt-3 min-h-14 text-sm leading-6 text-slate-600">{category.description}</p><span className="mt-6 inline-flex items-center gap-2 text-sm font-bold text-[#8A6A20]">Read the section <ArrowUpRight className="h-4 w-4 transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></span></Link>)}</div></section>
    <section className="border-y border-[#e8dfc8] bg-[#f4efe2]"><div className="mx-auto flex max-w-7xl flex-col gap-6 px-4 py-12 sm:px-6 md:flex-row md:items-center md:justify-between lg:px-8"><div><div className="mb-3 inline-flex items-center gap-2 text-sm font-bold text-[#8A6A20]"><Sparkles className="h-4 w-4" />Have a story in mind?</div><h2 className="text-2xl font-black">Can’t find the beat you’re looking for?</h2><p className="mt-2 text-slate-600">Tell us what would make planning your next trip easier.</p></div><Link href="/contact" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#19273A] px-5 py-3 font-bold text-white transition hover:bg-[#2A3F5F]">Suggest a category <ArrowUpRight className="h-4 w-4" /></Link></div></section>
  </main>;
}
