name: Automated Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

      - name: Create backup branch
        run: |
          BACKUP_BRANCH="backup/$(date +%Y-%m-%d)"
          git checkout -b $BACKUP_BRANCH
          git push origin $BACKUP_BRANCH

      - name: Upload to AWS S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Sync with S3
        run: |
          zip -r backup.zip .
          aws s3 cp backup.zip s3://globaltravelreport-backups/$(date +%Y-%m-%d)/backup.zip

      - name: Cleanup old backups
        run: |
          # Keep only last 30 days of backups
          aws s3 ls s3://globaltravelreport-backups/ | sort -r | tail -n +31 | awk '{print $2}' | xargs -I {} aws s3 rm s3://globaltravelreport-backups/{} 