name: Social Media Poster

on:
  # Run automatically after the daily stories workflow
  workflow_run:
    workflows: ["Daily Stories"]
    types:
      - completed

  # Run on schedule (2:30pm Sydney time = 04:30 UTC)
  schedule:
    - cron: '30 4 * * *'

  # Allow manual triggering
  workflow_dispatch:

jobs:
  post-to-social-media:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create logs directory
        run: mkdir -p logs

      - name: Check available API keys
        run: |
          echo "Checking available social media API keys..."

          # Check Twitter API keys
          if [ -n "${{ secrets.TWITTER_API_KEY }}" ] && [ -n "${{ secrets.TWITTER_API_SECRET }}" ] && [ -n "${{ secrets.TWITTER_ACCESS_TOKEN }}" ] && [ -n "${{ secrets.TWITTER_ACCESS_SECRET }}" ]; then
            echo "✅ Twitter API keys are available"
          else
            echo "⚠️ Twitter API keys are missing"
          fi

          # Check Facebook API keys
          if [ -n "${{ secrets.FACEBOOK_PAGE_ID }}" ] && [ -n "${{ secrets.FACEBOOK_ACCESS_TOKEN }}" ]; then
            echo "✅ Facebook API keys are available"
          else
            echo "⚠️ Facebook API keys are missing"
          fi

          # Check LinkedIn API keys
          if [ -n "${{ secrets.LINKEDIN_ACCESS_TOKEN }}" ]; then
            echo "✅ LinkedIn API keys are available"
          else
            echo "⚠️ LinkedIn API keys are missing"
          fi

          # Check Tumblr API keys
          if [ -n "${{ secrets.TUMBLR_API_KEY }}" ]; then
            echo "✅ Tumblr API keys are available"
          else
            echo "⚠️ Tumblr API keys are missing"
          fi

      - name: Post to social media
        run: node scripts/social-media-poster.js --post-all
        env:
          # Twitter API keys
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}

          # Facebook API keys
          FACEBOOK_PAGE_ID: ${{ secrets.FACEBOOK_PAGE_ID }}
          FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}

          # LinkedIn API keys
          LINKEDIN_CLIENT_ID: ${{ secrets.LINKEDIN_CLIENT_ID }}
          LINKEDIN_CLIENT_SECRET: ${{ secrets.LINKEDIN_CLIENT_SECRET }}
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}

          # Tumblr API keys
          TUMBLR_API_KEY: ${{ secrets.TUMBLR_API_KEY }}
          TUMBLR_CONSUMER_SECRET: ${{ secrets.TUMBLR_CONSUMER_SECRET }}
          TUMBLR_ACCESS_TOKEN: ${{ secrets.TUMBLR_ACCESS_TOKEN }}
          TUMBLR_ACCESS_TOKEN_SECRET: ${{ secrets.TUMBLR_ACCESS_TOKEN_SECRET }}
          TUMBLR_BLOG_NAME: 'globaltravelreport'

          # Site URL
          NEXT_PUBLIC_SITE_URL: 'https://www.globaltravelreport.com'

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: social-media-logs
          path: logs/social-media-poster.log
          retention-days: 7
